version: '3'

services:
  solr:
    container_name: nomenmatch-v2-solr
    build:
      context: ./compose/solr
      #dockerfile: ./compose/solr/Dockerfile
    image: nomenmatch-v2-solr:8
    ports:
      - "8983:8983"
    volumes:
      - ./solr-data:/var/solr/data
    command:
      - solr-precreate
      #- gettingstarted
  # nginx:
  #   image: nginx:latest
  #   ports:
  #       - "80:80"
  #   volumes:
  #       - ./:/code
  #       - ./compose/nginx-production:/etc/nginx/conf.d
  php:
    image: php:7-fpm
    volumes:
        - ./:/code
        - ./source-data:/code/source-data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.php.rule=Host(`match.taibif.tw`)"
      - "traefik.http.routers.php.entrypoints=websecure"
      - "traefik.http.routers.php.tls.certresolver=myresolver"
  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=catalogueoflife.taiwan@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      # - "8080:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

volumes:
  solr-data:
